package Sustainability;
// Generated Jan 18, 2013 4:54:08 PM by Hibernate Tools 3.2.1.GA



/**
 * Diversionsaving generated by hbm2java
 */
public class Diversionsaving  implements java.io.Serializable {


     private DiversionsavingId id;
     private Users users;
     private Category category;
     private Integer quantity;
     private Double landfillRate;
     private String unit;

    public Diversionsaving() {
    }

	
    public Diversionsaving(DiversionsavingId id, Category category) {
        this.id = id;
        this.category = category;
    }
    public Diversionsaving(DiversionsavingId id, Users users, Category category, Integer quantity, Double landfillRate, String unit) {
       this.id = id;
       this.users = users;
       this.category = category;
       this.quantity = quantity;
       this.landfillRate = landfillRate;
       this.unit = unit;
    }
   
    public DiversionsavingId getId() {
        return this.id;
    }
    
    public void setId(DiversionsavingId id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Double getLandfillRate() {
        return this.landfillRate;
    }
    
    public void setLandfillRate(Double landfillRate) {
        this.landfillRate = landfillRate;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }




}


