package Sustainability;
// Generated Feb 1, 2013 7:21:23 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * DiversionsavingId generated by hbm2java
 */
public class DiversionsavingId  implements java.io.Serializable {


     private String categoryName;
     private Date entrydate;

    public DiversionsavingId() {
    }

    public DiversionsavingId(String categoryName, Date date) {
       this.categoryName = categoryName;
       this.entrydate = date;
    }
   
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public Date getDate() {
        return this.entrydate;
    }
    
    public void setDate(Date date) {
        this.entrydate = date;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DiversionsavingId) ) return false;
		 DiversionsavingId castOther = ( DiversionsavingId ) other; 
         
		 return ( (this.getCategoryName()==castOther.getCategoryName()) || ( this.getCategoryName()!=null && castOther.getCategoryName()!=null && this.getCategoryName().equals(castOther.getCategoryName()) ) )
 && ( (this.getDate()==castOther.getDate()) || ( this.getDate()!=null && castOther.getDate()!=null && this.getDate().equals(castOther.getDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCategoryName() == null ? 0 : this.getCategoryName().hashCode() );
         result = 37 * result + ( getDate() == null ? 0 : this.getDate().hashCode() );
         return result;
   }   


}


