package Sustainability;
// Generated Feb 1, 2013 7:21:23 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Diversionsaving generated by hbm2java
 */
public class Diversionsaving  implements java.io.Serializable {


     private DiversionsavingId id;
     private Users users;
     private Category category;
     private Double quantity;
     private Double landfillRate;
     private String unit;
     private Date landfillDate;
     private Date date;
     private Double diversionSaving;

    public Diversionsaving() {
    }

	
    public Diversionsaving(DiversionsavingId id, Category category, Date date) {
        this.id = id;
        this.category = category;
        this.date=date;
    }


    
    public Diversionsaving(DiversionsavingId id, Date date,Users users, Category category, Double quantity, Double landfillRate, String unit, Date landfillDate, Double diversionSaving) {
       this.id = id;
       this.users = users;
       this.category = category;
       this.quantity = quantity;
       this.landfillRate = landfillRate;
       this.unit = unit;
       this.landfillDate = landfillDate;
       this.diversionSaving = diversionSaving;
       this.date=date;
    }
   
    public DiversionsavingId getId() {
        return this.id;
    }
    
    public void setId(DiversionsavingId id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
     public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }
    

    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Double getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }
    public Double getLandfillRate() {
        return this.landfillRate;
    }
    
    public void setLandfillRate(Double landfillRate) {
        this.landfillRate = landfillRate;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public Date getLandfillDate() {
        return this.landfillDate;
    }
    
    public void setLandfillDate(Date landfillDate) {
        this.landfillDate = landfillDate;
    }
    public Double getDiversionSaving() {
        return this.diversionSaving;
    }
    
    public void setDiversionSaving(Double diversionSaving) {
        this.diversionSaving = diversionSaving;
    }
}


