package Sustainability;
// Generated Jan 18, 2013 4:54:08 PM by Hibernate Tools 3.2.1.GA



/**
 * Revenue generated by hbm2java
 */
public class Revenue  implements java.io.Serializable {


     private RevenueId id;
     private Users users;
     private Category category;
     private Double quantity;
     private Float marketRate;
     private String unit;
     private Double amount;
     private String comment;
     private String transportationCost;

    public Revenue() {
    }

	
    public Revenue(RevenueId id, Category category) {
        this.id = id;
        this.category = category;
    }
    public Revenue(RevenueId id, Users users, Category category, Double quantity, Float marketRate, String unit, Double amount, String comment, String transportationCost) {
       this.id = id;
       this.users = users;
       this.category = category;
       this.quantity = quantity;
       this.marketRate = marketRate;
       this.unit = unit;
       this.amount = amount;
       this.comment = comment;
       this.transportationCost = transportationCost;
    }
   
    public RevenueId getId() {
        return this.id;
    }
    
    public void setId(RevenueId id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Double getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }
    public Float getMarketRate() {
        return this.marketRate;
    }
    
    public void setMarketRate(Float marketRate) {
        this.marketRate = marketRate;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getTransportationCost() {
        return this.transportationCost;
    }
    
    public void setTransportationCost(String transportationCost) {
        this.transportationCost = transportationCost;
    }




}


