package Sustainability;
// Generated Feb 1, 2013 7:21:23 PM by Hibernate Tools 3.2.1.GA

import java.math.BigInteger;
import java.util.Date;




/**
 * Revenue generated by hbm2java
 */
public class Revenue  implements java.io.Serializable {
     private Category category;
     private Date sellingdate;
     private Double quantity;
     private Users users;
     private Double marketRate;
     private String unit;
     private Double amount;
     private String comment;
     private Transportation transportation;

    public Revenue() {
    }

	
    public Revenue(Category category) {
        this.category = category;
    }
    public Revenue(Users users, Category category, Double quantity, Double marketRate, String unit, Double amount, String comment, String transportationCost) {
       this.users = users;
       this.category = category;
       this.quantity = quantity;
       this.marketRate = marketRate;
       this.unit = unit;
       this.amount = amount;
       this.comment = comment;
    }

    public Transportation getTransportation() {
        return transportation;
    }

    public void setTransportation(Transportation transportation) {
        this.transportation = transportation;
    }
   
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

//    public Long getLot() {
//        return lot;
//    }
//
//    public void setLot(Long lot) {
//        this.lot = lot;
//    }
    
    
    public Double getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }
    public Double getMarketRate() {
        return this.marketRate;
    }
    
    public void setMarketRate(Double marketRate) {
        this.marketRate = marketRate;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    public Date getSellingdate() {
        return sellingdate;
    }

    public void setSellingdate(Date sellingdate) {
        this.sellingdate = sellingdate;
    }
}


