package Sustainability;
// Generated Feb 1, 2013 7:21:23 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transportation generated by hbm2java
 */
public class Transportation  implements java.io.Serializable {


     private Date date;
     private Double cost;
     private Long lot;
     //private Set revenues = new HashSet(0);

    public Transportation() {
    }
    public Transportation(Date date) {
        this.date = date;
    }
    public Transportation(Date date, Double cost) {
       this.date = date;
       this.cost = cost;
    }
   
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Double getCost() {
        return this.cost;
    }
    
    public void setCost(Double cost) {
        this.cost = cost;
    }

    public Long getLot() {
        return lot;
    }

    public void setLot(Long lot) {
        this.lot = lot;
    }
}


